# Używamy obrazu serwera HTTP (np. Nginx)
FROM nginx:alpine

# Kopiujemy pliki frontendowe do katalogu publicznego w Nginx
COPY ./ /usr/share/nginx/html/

# Otwieramy port 80 (standardowy port HTTP)
EXPOSE 80
